export const productsData = [
      {
        name: "Keyboard",
        description: "A good gaming keyboard",
        category: "Gaming Peripheral",
        price: "$250.00",
        salePrice: "$230.00",
        brand: "Logitech",
        stock: 5,
      },
      {
        name: "Gaming Mouse",
        description: "High precision wireless mouse",
        category: "Gaming Peripheral",
        price: "$120.00",
        salePrice: "$100.00",
        brand: "Razer",
        stock: 10,
      },
      {
        name: "Gaming Headset",
        description: "Surround sound with noise-cancelling microphone",
        category: "Gaming Audio",
        price: "$150.00",
        salePrice: "$130.00",
        brand: "Corsair",
        stock: 7,
      },
      {
        name: "Mechanical Keyboard",
        description: "RGB mechanical keyboard with customizable keys",
        category: "Gaming Peripheral",
        price: "$300.00",
        salePrice: "$280.00",
        brand: "SteelSeries",
        stock: 12,
      },
      {
        name: "Gaming Chair",
        description: "Ergonomic gaming chair with lumbar support",
        category: "Gaming Furniture",
        price: "$400.00",
        salePrice: "$370.00",
        brand: "Secretlab",
        stock: 4,
      },
      {
        name: "Webcam",
        description: "HD webcam for streaming and video calls",
        category: "Gaming Accessory",
        price: "$80.00",
        salePrice: "$70.00",
        brand: "Logitech",
        stock: 15,
      },
      {
        name: "Gaming Monitor",
        description: "27-inch 4K gaming monitor with high refresh rate",
        category: "Monitor",
        price: "$600.00",
        salePrice: "$550.00",
        brand: "ASUS ROG",
        stock: 6,
      },
      {
        name: "VR Headset",
        description: "Immersive virtual reality headset for gaming",
        category: "Gaming Console",
        price: "$500.00",
        salePrice: "$450.00",
        brand: "Oculus (Meta)",
        stock: 8,
      },
      {
        name: "Graphics Card",
        description: "High-performance GPU for gaming and streaming",
        category: "PC Component",
        price: "$1,200.00",
        salePrice: "$1,100.00",
        brand: "NVIDIA",
        stock: 3,
      },
      {
        name: "Processor",
        description: "Advanced multi-core CPU for gaming PCs",
        category: "PC Component",
        price: "$700.00",
        salePrice: "$650.00",
        brand: "AMD",
        stock: 10,
      },
      {
        name: "Gaming Laptop",
        description: "High-performance laptop for gaming and work",
        category: "Laptop",
        price: "$1,500.00",
        salePrice: "$1,350.00",
        brand: "Alienware",
        stock: 5,
      },
      {
        name: "Gaming Console",
        description: "Next-gen gaming console with 4K support",
        category: "Gaming Console",
        price: "$500.00",
        salePrice: "$450.00",
        brand: "Sony PlayStation",
        stock: 7,
      },
      {
        name: "External Hard Drive",
        description: "1TB external drive for storing game data",
        category: "Storage",
        price: "$100.00",
        salePrice: "$90.00",
        brand: "Western Digital",
        stock: 20,
      },
      {
        name: "Cooling Pad",
        description: "Cooling pad for gaming laptops",
        category: "Gaming Accessory",
        price: "$40.00",
        salePrice: "$35.00",
        brand: "Cooler Master",
        stock: 12,
      },
      {
        name: "Game Controller",
        description: "Wireless controller for gaming consoles and PCs",
        category: "Gaming Peripheral",
        price: "$60.00",
        salePrice: "$50.00",
        brand: "Microsoft Xbox",
        stock: 15,
      },
      {
        name: "SSD",
        description: "Fast 1TB SSD for quick game loading",
        category: "Storage",
        price: "$150.00",
        salePrice: "$140.00",
        brand: "Samsung",
        stock: 8,
      },
      {
        name: "Game Capture Card",
        description: "4K game capture card for streaming",
        category: "Gaming Accessory",
        price: "$200.00",
        salePrice: "$180.00",
        brand: "Elgato",
        stock: 5,
      },
      {
        name: "Wireless Gaming Mouse",
        description: "Ultra-lightweight wireless gaming mouse",
        category: "Gaming Peripheral",
        price: "$110.00",
        salePrice: "$100.00",
        brand: "Glorious PC Gaming Race",
        stock: 10,
      },
      {
        name: "Gaming Desk",
        description: "Large gaming desk with RGB lighting",
        category: "Gaming Furniture",
        price: "$350.00",
        salePrice: "$330.00",
        brand: "DXRacer",
        stock: 6,
      },
      {
        name: "Headphone Stand",
        description: "RGB headphone stand with USB ports",
        category: "Gaming Accessory",
        price: "$50.00",
        salePrice: "$45.00",
        brand: "Razer",
        stock: 20,
      },
    ];
    